/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package market;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ranat
 */
public class Customer extends javax.swing.JFrame {

    dbConnn ob1 = new dbConnn();
    
    Connection Con;
    PreparedStatement psmt;
    
    
    public Customer(Login login) {
        initComponents();
        try{
        String text = login.getTextFiel().getText();
       lbl_welcome.setText(text);
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }
    public Customer() {
    initComponents();
}
    

   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        btn_reg4 = new com.k33ptoo.components.KButton();
        btn_reg5 = new com.k33ptoo.components.KButton();
        btn_reg6 = new com.k33ptoo.components.KButton();
        btn_reg7 = new com.k33ptoo.components.KButton();
        btn_reg10 = new com.k33ptoo.components.KButton();
        jPanel1 = new javax.swing.JPanel();
        tbp_cus = new raven.tabbed.TabbedPaneCustom();
        Dashboard = new javax.swing.JPanel();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        lbl_welcome = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        services = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btn_reg8 = new com.k33ptoo.components.KButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        txt_price = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        settings = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_crdName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_crdNum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_crdEx = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_crdCvc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_Uuser = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_Ucur_pw = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_Unew_pw = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_reg9 = new com.k33ptoo.components.KButton();
        btn_addcrd = new com.k33ptoo.components.KButton();

        jLabel6.setText("Credit Card Details");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel1.setkGradientFocus(300);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 153, 204));

        btn_reg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/8_s.png"))); // NOI18N
        btn_reg4.setText("Services");
        btn_reg4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btn_reg4.setIconTextGap(40);
        btn_reg4.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg4.setkEndColor(new java.awt.Color(0, 153, 204));
        btn_reg4.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        btn_reg4.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg4.setkHoverStartColor(new java.awt.Color(0, 204, 255));
        btn_reg4.setkPressedColor(new java.awt.Color(0, 153, 204));
        btn_reg4.setkSelectedColor(new java.awt.Color(0, 153, 153));
        btn_reg4.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg4ActionPerformed(evt);
            }
        });

        btn_reg5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/7_s.png"))); // NOI18N
        btn_reg5.setText("Settings");
        btn_reg5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btn_reg5.setIconTextGap(40);
        btn_reg5.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg5.setkEndColor(new java.awt.Color(0, 153, 204));
        btn_reg5.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        btn_reg5.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg5.setkHoverStartColor(new java.awt.Color(0, 204, 255));
        btn_reg5.setkPressedColor(new java.awt.Color(0, 153, 204));
        btn_reg5.setkSelectedColor(new java.awt.Color(0, 153, 153));
        btn_reg5.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg5ActionPerformed(evt);
            }
        });

        btn_reg6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/6_s.png"))); // NOI18N
        btn_reg6.setText("profile");
        btn_reg6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btn_reg6.setIconTextGap(40);
        btn_reg6.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg6.setkEndColor(new java.awt.Color(0, 153, 204));
        btn_reg6.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        btn_reg6.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg6.setkHoverStartColor(new java.awt.Color(0, 204, 255));
        btn_reg6.setkPressedColor(new java.awt.Color(0, 153, 204));
        btn_reg6.setkSelectedColor(new java.awt.Color(0, 153, 153));
        btn_reg6.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg6ActionPerformed(evt);
            }
        });

        btn_reg7.setText("Dashboard");
        btn_reg7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btn_reg7.setIconTextGap(40);
        btn_reg7.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg7.setkEndColor(new java.awt.Color(0, 153, 204));
        btn_reg7.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        btn_reg7.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg7.setkHoverStartColor(new java.awt.Color(0, 204, 255));
        btn_reg7.setkPressedColor(new java.awt.Color(0, 153, 204));
        btn_reg7.setkSelectedColor(new java.awt.Color(0, 153, 153));
        btn_reg7.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg7ActionPerformed(evt);
            }
        });

        btn_reg10.setText("Logout");
        btn_reg10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btn_reg10.setIconTextGap(40);
        btn_reg10.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg10.setkEndColor(new java.awt.Color(0, 153, 204));
        btn_reg10.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        btn_reg10.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg10.setkHoverStartColor(new java.awt.Color(0, 204, 255));
        btn_reg10.setkPressedColor(new java.awt.Color(0, 153, 204));
        btn_reg10.setkSelectedColor(new java.awt.Color(0, 153, 153));
        btn_reg10.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_reg4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_reg6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_reg5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(btn_reg7, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(btn_reg10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(btn_reg7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_reg4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_reg5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_reg6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(btn_reg10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        getContentPane().add(kGradientPanel1, java.awt.BorderLayout.LINE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tbp_cus.setSelectedColor(new java.awt.Color(255, 255, 255));

        Dashboard.setBackground(new java.awt.Color(255, 255, 255));

        kGradientPanel2.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkBorderRadius(30);
        kGradientPanel2.setkEndColor(new java.awt.Color(204, 0, 153));

        lbl_welcome.setFont(new java.awt.Font("STHupo", 0, 29)); // NOI18N
        lbl_welcome.setForeground(new java.awt.Color(255, 255, 255));
        lbl_welcome.setText("WELCOME");

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lbl_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(548, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lbl_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(402, Short.MAX_VALUE))
        );

        tbp_cus.addTab("", Dashboard);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                ""
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        tbp_cus.addTab("", jPanel3);

        services.setBackground(new java.awt.Color(255, 255, 255));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "25 channel 30 Days" }));

        jLabel2.setText("Select Service Type");

        btn_reg8.setText("Subscribe");
        btn_reg8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btn_reg8.setIconTextGap(40);
        btn_reg8.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg8.setkEndColor(new java.awt.Color(0, 153, 204));
        btn_reg8.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        btn_reg8.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg8.setkHoverStartColor(new java.awt.Color(0, 204, 255));
        btn_reg8.setkPressedColor(new java.awt.Color(0, 153, 204));
        btn_reg8.setkSelectedColor(new java.awt.Color(0, 153, 153));
        btn_reg8.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg8ActionPerformed(evt);
            }
        });

        jLabel3.setText("Select Service provider ");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Other payments", "Water bill", "Electicity bill", "Telecommunication bill", " ", " " }));

        jLabel13.setText("Select Service");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Free Sat" }));

        txt_price.setText("0.00");
        txt_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_priceActionPerformed(evt);
            }
        });

        jLabel14.setText("Price");

        javax.swing.GroupLayout servicesLayout = new javax.swing.GroupLayout(services);
        services.setLayout(servicesLayout);
        servicesLayout.setHorizontalGroup(
            servicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, servicesLayout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addGroup(servicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(servicesLayout.createSequentialGroup()
                        .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(btn_reg8, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(151, 151, 151))
        );
        servicesLayout.setVerticalGroup(
            servicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicesLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(servicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reg8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        tbp_cus.addTab("", services);

        settings.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Password Change");

        jLabel4.setText("Card Holders Name");

        jLabel5.setText("Card Number");

        txt_crdEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_crdExActionPerformed(evt);
            }
        });

        jLabel7.setText("Expir Date");

        jLabel8.setText("CVC");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Credit Card Details");

        jLabel10.setText("Current Password");

        jLabel11.setText("User Name");

        jLabel12.setText("New password");

        btn_reg9.setText("update ");
        btn_reg9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btn_reg9.setIconTextGap(40);
        btn_reg9.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg9.setkEndColor(new java.awt.Color(0, 153, 204));
        btn_reg9.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        btn_reg9.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg9.setkHoverStartColor(new java.awt.Color(0, 204, 255));
        btn_reg9.setkPressedColor(new java.awt.Color(0, 153, 204));
        btn_reg9.setkSelectedColor(new java.awt.Color(0, 153, 153));
        btn_reg9.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg9ActionPerformed(evt);
            }
        });

        btn_addcrd.setText("add card");
        btn_addcrd.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btn_addcrd.setIconTextGap(40);
        btn_addcrd.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_addcrd.setkEndColor(new java.awt.Color(0, 153, 204));
        btn_addcrd.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        btn_addcrd.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_addcrd.setkHoverStartColor(new java.awt.Color(0, 204, 255));
        btn_addcrd.setkPressedColor(new java.awt.Color(0, 153, 204));
        btn_addcrd.setkSelectedColor(new java.awt.Color(0, 153, 153));
        btn_addcrd.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_addcrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addcrdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingsLayout = new javax.swing.GroupLayout(settings);
        settings.setLayout(settingsLayout);
        settingsLayout.setHorizontalGroup(
            settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingsLayout.createSequentialGroup()
                        .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txt_Ucur_pw, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Uuser, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_crdName, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txt_crdEx, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_crdNum, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txt_crdCvc, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(settingsLayout.createSequentialGroup()
                        .addComponent(txt_Unew_pw, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                        .addComponent(btn_reg9, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
            .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsLayout.createSequentialGroup()
                    .addContainerGap(614, Short.MAX_VALUE)
                    .addComponent(btn_addcrd, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(76, 76, 76)))
        );
        settingsLayout.setVerticalGroup(
            settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_crdName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_crdNum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_crdEx, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_crdCvc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Uuser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Ucur_pw, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Unew_pw, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reg9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(settingsLayout.createSequentialGroup()
                    .addGap(286, 286, 286)
                    .addComponent(btn_addcrd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(248, Short.MAX_VALUE)))
        );

        tbp_cus.addTab("", settings);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbp_cus, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbp_cus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_reg4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg4ActionPerformed
            tbp_cus.setSelectedIndex(2);
    }//GEN-LAST:event_btn_reg4ActionPerformed

    private void btn_reg5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg5ActionPerformed
             tbp_cus.setSelectedIndex(3);
    }//GEN-LAST:event_btn_reg5ActionPerformed

    private void btn_reg6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_reg6ActionPerformed

    private void btn_reg7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg7ActionPerformed
        tbp_cus.setSelectedIndex(0);
    }//GEN-LAST:event_btn_reg7ActionPerformed

    private void btn_reg8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg8ActionPerformed
       txt_price.setEditable(false);
       
        
    }//GEN-LAST:event_btn_reg8ActionPerformed

    private void txt_crdExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_crdExActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_crdExActionPerformed

    private void btn_reg9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg9ActionPerformed
      Con = ob1.getConnection();
       String name =txt_Uuser.getText();
       String pw = txt_Unew_pw.getText();
       
        try{
            //methana hdnd thiynw
             psmt = Con.prepareStatement("Update register SET password = ? WHERE user_name = ?");

                psmt.setString(1, name);
                psmt.setString(2,pw);
              
                psmt.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Password updated successfully.");
               txt_Uuser.setText(null);
               txt_Ucur_pw.setText(null);
               txt_Unew_pw.setText(null);
        
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
            System.out.println(e);
            
        }
       
    }//GEN-LAST:event_btn_reg9ActionPerformed

    private void btn_addcrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addcrdActionPerformed
       
        Con = ob1.getConnection();
        
        String crdName = txt_crdName.getText();
        String crdNum = txt_crdNum.getText();
        String cvc = txt_crdCvc.getText();
        
        try{
            //methana hdnd thiynw
             psmt = Con.prepareStatement("Insert into personal(name,password)values(?,?)");
                psmt.setString(1, crdName);
                psmt.setString(2,crdNum);
                psmt.setString(3,cvc);
                psmt.executeUpdate();
        
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
            
        }
        
        
    }//GEN-LAST:event_btn_addcrdActionPerformed

    private void txt_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_priceActionPerformed

    private void btn_reg10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg10ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Are you sure to Logout from the Current session!", "alert", HEIGHT);
        
            Login l1 = new Login();
            l1.setVisible(true);
            this.dispose();
        
    }//GEN-LAST:event_btn_reg10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Dashboard;
    private com.k33ptoo.components.KButton btn_addcrd;
    private com.k33ptoo.components.KButton btn_reg10;
    private com.k33ptoo.components.KButton btn_reg4;
    private com.k33ptoo.components.KButton btn_reg5;
    private com.k33ptoo.components.KButton btn_reg6;
    private com.k33ptoo.components.KButton btn_reg7;
    private com.k33ptoo.components.KButton btn_reg8;
    private com.k33ptoo.components.KButton btn_reg9;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    public javax.swing.JLabel lbl_welcome;
    private javax.swing.JPanel services;
    private javax.swing.JPanel settings;
    private raven.tabbed.TabbedPaneCustom tbp_cus;
    private javax.swing.JTextField txt_Ucur_pw;
    private javax.swing.JTextField txt_Unew_pw;
    private javax.swing.JTextField txt_Uuser;
    private javax.swing.JTextField txt_crdCvc;
    private javax.swing.JTextField txt_crdEx;
    private javax.swing.JTextField txt_crdName;
    private javax.swing.JTextField txt_crdNum;
    private javax.swing.JTextField txt_price;
    // End of variables declaration//GEN-END:variables
}
