/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package market;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ranat
 */
public class Login extends javax.swing.JFrame {
    
    dbConnn ob1 = new dbConnn();
    
    Connection Con;
    PreparedStatement psmt;
    

    /**
     * Creates new form Login
     */
    public Login() {

        initComponents();

       

    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        pnl_start = new javax.swing.JPanel();
        btn_reg2 = new com.k33ptoo.components.KButton();
        btn_reg3 = new com.k33ptoo.components.KButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnl_register = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_pw_con = new javax.swing.JPasswordField();
        btn_reg5 = new com.k33ptoo.components.KButton();
        jLabel7 = new javax.swing.JLabel();
        txt_pw = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_reg4 = new com.k33ptoo.components.KButton();
        txt_name = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txt_user_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_pw_login = new javax.swing.JPasswordField();
        btn_reg12 = new com.k33ptoo.components.KButton();
        btn_reg13 = new com.k33ptoo.components.KButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_com_name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_com_pw = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_com_pw_con = new javax.swing.JPasswordField();
        btn_reg7 = new com.k33ptoo.components.KButton();
        btn_reg8 = new com.k33ptoo.components.KButton();
        jPanel5 = new javax.swing.JPanel();
        btn_reg9 = new com.k33ptoo.components.KButton();
        btn_reg10 = new com.k33ptoo.components.KButton();
        jLabel11 = new javax.swing.JLabel();
        btn_reg11 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new javax.swing.OverlayLayout(jPanel2));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/10782754-19197292.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6);

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 520, 610));

        tabs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnl_start.setBackground(new java.awt.Color(255, 255, 255));
        pnl_start.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_reg2.setText("Register");
        btn_reg2.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg2.setkEndColor(new java.awt.Color(0, 204, 255));
        btn_reg2.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        btn_reg2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg2.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_reg2.setkPressedColor(new java.awt.Color(0, 204, 255));
        btn_reg2.setkSelectedColor(new java.awt.Color(0, 153, 255));
        btn_reg2.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg2ActionPerformed(evt);
            }
        });
        pnl_start.add(btn_reg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 321, -1));

        btn_reg3.setText("Login");
        btn_reg3.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg3.setkEndColor(new java.awt.Color(0, 204, 255));
        btn_reg3.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        btn_reg3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg3.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_reg3.setkPressedColor(new java.awt.Color(0, 204, 255));
        btn_reg3.setkSelectedColor(new java.awt.Color(0, 153, 255));
        btn_reg3.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg3ActionPerformed(evt);
            }
        });
        pnl_start.add(btn_reg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 321, -1));

        jLabel12.setText("Already have an account!");
        pnl_start.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 140, -1));

        jLabel13.setText("New to the App! Click Register to create new account");
        pnl_start.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        tabs.addTab("tab1", pnl_start);

        pnl_register.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Enter Password");

        btn_reg5.setText("Back");
        btn_reg5.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg5.setkEndColor(new java.awt.Color(0, 204, 255));
        btn_reg5.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        btn_reg5.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg5.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_reg5.setkPressedColor(new java.awt.Color(0, 204, 255));
        btn_reg5.setkSelectedColor(new java.awt.Color(0, 153, 255));
        btn_reg5.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg5ActionPerformed(evt);
            }
        });

        jLabel7.setText("Confirm Password");

        jLabel3.setText("Enter Name :");

        btn_reg4.setText("Register");
        btn_reg4.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg4.setkEndColor(new java.awt.Color(0, 204, 255));
        btn_reg4.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        btn_reg4.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg4.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_reg4.setkPressedColor(new java.awt.Color(0, 204, 255));
        btn_reg4.setkSelectedColor(new java.awt.Color(0, 153, 255));
        btn_reg4.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_registerLayout = new javax.swing.GroupLayout(pnl_register);
        pnl_register.setLayout(pnl_registerLayout);
        pnl_registerLayout.setHorizontalGroup(
            pnl_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_registerLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(pnl_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_pw_con, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_pw, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_registerLayout.createSequentialGroup()
                        .addGroup(pnl_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_reg5, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_reg4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)))
                .addGap(74, 74, 74))
        );
        pnl_registerLayout.setVerticalGroup(
            pnl_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_registerLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(8, 8, 8)
                .addComponent(txt_pw, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pw_con, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_reg4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_reg5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        tabs.addTab("tab2", pnl_register);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Enter User Name");

        jLabel2.setText("Enter Password");

        btn_reg12.setText("Login");
        btn_reg12.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg12.setkEndColor(new java.awt.Color(0, 204, 255));
        btn_reg12.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        btn_reg12.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg12.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_reg12.setkPressedColor(new java.awt.Color(0, 204, 255));
        btn_reg12.setkSelectedColor(new java.awt.Color(0, 153, 255));
        btn_reg12.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg12ActionPerformed(evt);
            }
        });

        btn_reg13.setText("Back");
        btn_reg13.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg13.setkEndColor(new java.awt.Color(0, 204, 255));
        btn_reg13.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        btn_reg13.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg13.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_reg13.setkPressedColor(new java.awt.Color(0, 204, 255));
        btn_reg13.setkSelectedColor(new java.awt.Color(0, 153, 255));
        btn_reg13.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_user_name, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_pw_login)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_reg13, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_reg12, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pw_login, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_reg12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_reg13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        tabs.addTab("tab3", jPanel1);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Service or Company Name");

        jLabel9.setText("Create a Password");

        jLabel10.setText("Confirm Password");

        btn_reg7.setText("Register");
        btn_reg7.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg7.setkEndColor(new java.awt.Color(0, 204, 255));
        btn_reg7.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        btn_reg7.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg7.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_reg7.setkPressedColor(new java.awt.Color(0, 204, 255));
        btn_reg7.setkSelectedColor(new java.awt.Color(0, 153, 255));
        btn_reg7.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg7ActionPerformed(evt);
            }
        });

        btn_reg8.setText("Back");
        btn_reg8.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg8.setkEndColor(new java.awt.Color(0, 204, 255));
        btn_reg8.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        btn_reg8.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg8.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_reg8.setkPressedColor(new java.awt.Color(0, 204, 255));
        btn_reg8.setkSelectedColor(new java.awt.Color(0, 153, 255));
        btn_reg8.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_com_pw_con, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_com_pw, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_com_name, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_reg8, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_reg7, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)))
                .addGap(74, 74, 74))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_com_name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(8, 8, 8)
                .addComponent(txt_com_pw, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_com_pw_con, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_reg7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_reg8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        tabs.addTab("tab4", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btn_reg9.setText("As a Service provider/Company");
        btn_reg9.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg9.setkEndColor(new java.awt.Color(0, 204, 255));
        btn_reg9.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        btn_reg9.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg9.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_reg9.setkPressedColor(new java.awt.Color(0, 204, 255));
        btn_reg9.setkSelectedColor(new java.awt.Color(0, 153, 255));
        btn_reg9.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg9ActionPerformed(evt);
            }
        });

        btn_reg10.setText("Back");
        btn_reg10.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg10.setkEndColor(new java.awt.Color(0, 204, 255));
        btn_reg10.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        btn_reg10.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg10.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_reg10.setkPressedColor(new java.awt.Color(0, 204, 255));
        btn_reg10.setkSelectedColor(new java.awt.Color(0, 153, 255));
        btn_reg10.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg10ActionPerformed(evt);
            }
        });

        jLabel11.setText("Select Account type to register");

        btn_reg11.setText("As a Customer");
        btn_reg11.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg11.setkEndColor(new java.awt.Color(0, 204, 255));
        btn_reg11.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        btn_reg11.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg11.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_reg11.setkPressedColor(new java.awt.Color(0, 204, 255));
        btn_reg11.setkSelectedColor(new java.awt.Color(0, 153, 255));
        btn_reg11.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_reg11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_reg9, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_reg10, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(29, 29, 29)
                .addComponent(btn_reg9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btn_reg11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btn_reg10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );

        tabs.addTab("tab5", jPanel5);

        jPanel3.add(tabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 500, 610));
        tabs.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1014, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    private void btn_reg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg2ActionPerformed
        tabs.setSelectedIndex(4);
    }//GEN-LAST:event_btn_reg2ActionPerformed

    private void btn_reg3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg3ActionPerformed
        tabs.setSelectedIndex(2);
    }//GEN-LAST:event_btn_reg3ActionPerformed

    private void btn_reg4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg4ActionPerformed
           
          Con = ob1.getConnection();
            
            
        
            String name = txt_name.getText();
            String psw = txt_pw.getText();
            String pw = txt_pw_con.getText();
            
             if (txt_name.getText().isEmpty() || txt_pw.getText().isEmpty()||txt_pw_con.getText().isEmpty()) {
                
                 JOptionPane.showMessageDialog(null, "Fill all the Fields!", "Info", JOptionPane.INFORMATION_MESSAGE);
             
             }else{
             
             if (psw == null ? pw == null : psw.equals(pw))
            {
                JOptionPane.showMessageDialog(null, "Registed Success!", "Info", JOptionPane.INFORMATION_MESSAGE);
            }else
            {
                JOptionPane.showMessageDialog(null, "Registed Unsuccess!", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
            
            try{
                
                psmt = Con.prepareStatement("Insert into register(user_name,password)values(?,?)");
                psmt.setString(1, name);
                psmt.setString(2,pw);
                psmt.executeUpdate();
               } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
             
             }
            
            
            
        }
            
    }//GEN-LAST:event_btn_reg4ActionPerformed

    private void btn_reg5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg5ActionPerformed
        tabs.setSelectedIndex(4);
    }//GEN-LAST:event_btn_reg5ActionPerformed

    private void btn_reg7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg7ActionPerformed
       
        Con = ob1.getConnection();
        
        String com_name = txt_com_name.getText();
        String com_psw = txt_com_pw.getText();
        String com_pw =txt_com_pw_con.getText();
        
        if(txt_com_name.getText().isEmpty()||txt_com_pw.getText().isEmpty()||txt_com_pw_con.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "fields cannot be empty!");
        }else{
        
            if(com_psw.equals(com_pw)){
        try{
            
             psmt=Con.prepareStatement("Insert into register_com(com_name,pw)values(?,?)");
             psmt.setString(1,com_name);
             psmt.setString(2, com_pw);
             psmt.executeUpdate();
             
            JOptionPane.showMessageDialog(rootPane, "Registration succsess!");
        }catch(Exception e)
        {
           JOptionPane.showMessageDialog(rootPane, e);
        }
        }else{
                JOptionPane.showMessageDialog(rootPane, "passwods not match!");
            }
        
        }
        
    }//GEN-LAST:event_btn_reg7ActionPerformed

    private void btn_reg8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg8ActionPerformed
       tabs.setSelectedIndex(4);
    }//GEN-LAST:event_btn_reg8ActionPerformed

    private void btn_reg9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg9ActionPerformed
        tabs.setSelectedIndex(3);
    }//GEN-LAST:event_btn_reg9ActionPerformed

    private void btn_reg10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg10ActionPerformed
        tabs.setSelectedIndex(0);
    }//GEN-LAST:event_btn_reg10ActionPerformed

    private void btn_reg11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg11ActionPerformed
        tabs.setSelectedIndex(1);
    }//GEN-LAST:event_btn_reg11ActionPerformed

    private void btn_reg12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg12ActionPerformed
        Con = ob1.getConnection();
        
        String name = txt_user_name.getText();
        String pw = txt_pw_login.getText();
        
        if(name.isEmpty()||pw.isEmpty()){
            
            JOptionPane.showMessageDialog(rootPane, "Enter user name and password to login!");
            
        }else
        try
        {
           psmt = Con.prepareStatement("Select * from register WHERE user_name = ? AND password = ?");
           psmt.setString(1,name);
           psmt.setString(2, pw);
           psmt.executeQuery();
           JOptionPane.showMessageDialog(rootPane, "Success!");
           
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btn_reg12ActionPerformed

    private void btn_reg13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_reg13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btn_reg10;
    private com.k33ptoo.components.KButton btn_reg11;
    private com.k33ptoo.components.KButton btn_reg12;
    private com.k33ptoo.components.KButton btn_reg13;
    private com.k33ptoo.components.KButton btn_reg2;
    private com.k33ptoo.components.KButton btn_reg3;
    private com.k33ptoo.components.KButton btn_reg4;
    private com.k33ptoo.components.KButton btn_reg5;
    private com.k33ptoo.components.KButton btn_reg7;
    private com.k33ptoo.components.KButton btn_reg8;
    private com.k33ptoo.components.KButton btn_reg9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel pnl_register;
    private javax.swing.JPanel pnl_start;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTextField txt_com_name;
    private javax.swing.JTextField txt_com_pw;
    private javax.swing.JPasswordField txt_com_pw_con;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_pw;
    private javax.swing.JPasswordField txt_pw_con;
    private javax.swing.JPasswordField txt_pw_login;
    private javax.swing.JTextField txt_user_name;
    // End of variables declaration//GEN-END:variables
}
