/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package market;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.*;




/**
 *
 * @author ranat
 */
public class Login extends javax.swing.JFrame {
    
    dbConnn ob1 = new dbConnn();
    
    Connection Con;
    PreparedStatement psmt;
    
   
   
    

    /**
     * Creates new form Login
     */
    public Login() {

        initComponents();

       

    }
    public JTextField getTextFiel(){
    
        return txt_user_name;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        pnl_start = new javax.swing.JPanel();
        btn_reg2 = new com.k33ptoo.components.KButton();
        btn_reg3 = new com.k33ptoo.components.KButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnl_register = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_pw_con = new javax.swing.JPasswordField();
        btn_reg5 = new com.k33ptoo.components.KButton();
        jLabel7 = new javax.swing.JLabel();
        txt_pw = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_reg_cus = new com.k33ptoo.components.KButton();
        txt_name = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        panel_login = new javax.swing.JPanel();
        txt_user_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_pw_login = new javax.swing.JPasswordField();
        btn_reg12 = new com.k33ptoo.components.KButton();
        btn_reg13 = new com.k33ptoo.components.KButton();
        service_provider_tgl = new toggle.ToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_com_name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_com_pw = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_com_pw_con = new javax.swing.JPasswordField();
        btn_reg_com = new com.k33ptoo.components.KButton();
        btn_reg8 = new com.k33ptoo.components.KButton();
        pannel_acc_type = new javax.swing.JPanel();
        btn_reg9 = new com.k33ptoo.components.KButton();
        btn_reg10 = new com.k33ptoo.components.KButton();
        jLabel11 = new javax.swing.JLabel();
        btn_reg11 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new javax.swing.OverlayLayout(jPanel2));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/10782754-19197292.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6);

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 520, 610));

        tabs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnl_start.setBackground(new java.awt.Color(255, 255, 255));
        pnl_start.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_reg2.setText("Register");
        btn_reg2.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg2.setkEndColor(new java.awt.Color(0, 204, 255));
        btn_reg2.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        btn_reg2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg2.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_reg2.setkPressedColor(new java.awt.Color(0, 204, 255));
        btn_reg2.setkSelectedColor(new java.awt.Color(0, 153, 255));
        btn_reg2.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg2ActionPerformed(evt);
            }
        });
        pnl_start.add(btn_reg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 321, -1));

        btn_reg3.setText("Login");
        btn_reg3.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg3.setkEndColor(new java.awt.Color(0, 204, 255));
        btn_reg3.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        btn_reg3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg3.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_reg3.setkPressedColor(new java.awt.Color(0, 204, 255));
        btn_reg3.setkSelectedColor(new java.awt.Color(0, 153, 255));
        btn_reg3.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg3ActionPerformed(evt);
            }
        });
        pnl_start.add(btn_reg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 321, -1));

        jLabel12.setText("Already have an account!");
        pnl_start.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 140, -1));

        jLabel13.setText("New to the App! Click Register to create new account");
        pnl_start.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        tabs.addTab("tab1", pnl_start);

        pnl_register.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Create a Password :");

        btn_reg5.setText("Back");
        btn_reg5.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg5.setkEndColor(new java.awt.Color(0, 204, 255));
        btn_reg5.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        btn_reg5.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg5.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_reg5.setkPressedColor(new java.awt.Color(0, 204, 255));
        btn_reg5.setkSelectedColor(new java.awt.Color(0, 153, 255));
        btn_reg5.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg5ActionPerformed(evt);
            }
        });

        jLabel7.setText("Confirm Password");

        jLabel3.setText("Enter Name :");

        btn_reg_cus.setText("Register");
        btn_reg_cus.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg_cus.setkEndColor(new java.awt.Color(0, 204, 255));
        btn_reg_cus.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        btn_reg_cus.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg_cus.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_reg_cus.setkPressedColor(new java.awt.Color(0, 204, 255));
        btn_reg_cus.setkSelectedColor(new java.awt.Color(0, 153, 255));
        btn_reg_cus.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg_cus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg_cusActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/market/icons8-close-48.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_registerLayout = new javax.swing.GroupLayout(pnl_register);
        pnl_register.setLayout(pnl_registerLayout);
        pnl_registerLayout.setHorizontalGroup(
            pnl_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_registerLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(pnl_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_registerLayout.createSequentialGroup()
                        .addGroup(pnl_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_pw_con, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_pw, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_registerLayout.createSequentialGroup()
                                .addGroup(pnl_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_reg5, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_reg_cus, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_registerLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        pnl_registerLayout.setVerticalGroup(
            pnl_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_registerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addGap(114, 114, 114)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(8, 8, 8)
                .addComponent(txt_pw, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pw_con, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_reg_cus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_reg5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt_name.getAccessibleContext().setAccessibleName("");

        tabs.addTab("tab2", pnl_register);

        panel_login.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText(" User Name");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Password");

        btn_reg12.setText("Login");
        btn_reg12.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg12.setkEndColor(new java.awt.Color(0, 204, 255));
        btn_reg12.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        btn_reg12.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg12.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_reg12.setkPressedColor(new java.awt.Color(0, 204, 255));
        btn_reg12.setkSelectedColor(new java.awt.Color(0, 153, 255));
        btn_reg12.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg12ActionPerformed(evt);
            }
        });

        btn_reg13.setText("Back");
        btn_reg13.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg13.setkEndColor(new java.awt.Color(0, 204, 255));
        btn_reg13.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        btn_reg13.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg13.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_reg13.setkPressedColor(new java.awt.Color(0, 204, 255));
        btn_reg13.setkSelectedColor(new java.awt.Color(0, 153, 255));
        btn_reg13.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg13ActionPerformed(evt);
            }
        });

        service_provider_tgl.setForeground(new java.awt.Color(0, 161, 228));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("I am Service provider");

        javax.swing.GroupLayout panel_loginLayout = new javax.swing.GroupLayout(panel_login);
        panel_login.setLayout(panel_loginLayout);
        panel_loginLayout.setHorizontalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_pw_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(txt_user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel_loginLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel2))))
                .addGap(64, 64, 64))
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_reg13, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reg12, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(service_provider_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_loginLayout.setVerticalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_pw_login, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(service_provider_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_reg12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_reg13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );

        tabs.addTab("tab3", panel_login);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Service or Company Name");

        jLabel9.setText("Create a Password");

        jLabel10.setText("Confirm Password");

        btn_reg_com.setText("Register");
        btn_reg_com.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg_com.setkEndColor(new java.awt.Color(0, 204, 255));
        btn_reg_com.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        btn_reg_com.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg_com.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_reg_com.setkPressedColor(new java.awt.Color(0, 204, 255));
        btn_reg_com.setkSelectedColor(new java.awt.Color(0, 153, 255));
        btn_reg_com.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg_com.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg_comActionPerformed(evt);
            }
        });

        btn_reg8.setText("Back");
        btn_reg8.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg8.setkEndColor(new java.awt.Color(0, 204, 255));
        btn_reg8.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        btn_reg8.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg8.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_reg8.setkPressedColor(new java.awt.Color(0, 204, 255));
        btn_reg8.setkSelectedColor(new java.awt.Color(0, 153, 255));
        btn_reg8.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_com_pw_con, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_com_pw, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_com_name, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_reg8, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_reg_com, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)))
                .addGap(74, 74, 74))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_com_name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(8, 8, 8)
                .addComponent(txt_com_pw, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_com_pw_con, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_reg_com, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_reg8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        tabs.addTab("tab4", jPanel4);

        pannel_acc_type.setBackground(new java.awt.Color(255, 255, 255));

        btn_reg9.setText("As a Service provider/Company");
        btn_reg9.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg9.setkEndColor(new java.awt.Color(0, 204, 255));
        btn_reg9.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        btn_reg9.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg9.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_reg9.setkPressedColor(new java.awt.Color(0, 204, 255));
        btn_reg9.setkSelectedColor(new java.awt.Color(0, 153, 255));
        btn_reg9.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg9ActionPerformed(evt);
            }
        });

        btn_reg10.setText("Back");
        btn_reg10.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg10.setkEndColor(new java.awt.Color(0, 204, 255));
        btn_reg10.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        btn_reg10.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg10.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_reg10.setkPressedColor(new java.awt.Color(0, 204, 255));
        btn_reg10.setkSelectedColor(new java.awt.Color(0, 153, 255));
        btn_reg10.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg10ActionPerformed(evt);
            }
        });

        jLabel11.setText("Select Account type to register");

        btn_reg11.setText("As a Customer");
        btn_reg11.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        btn_reg11.setkEndColor(new java.awt.Color(0, 204, 255));
        btn_reg11.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        btn_reg11.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_reg11.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btn_reg11.setkPressedColor(new java.awt.Color(0, 204, 255));
        btn_reg11.setkSelectedColor(new java.awt.Color(0, 153, 255));
        btn_reg11.setkStartColor(new java.awt.Color(0, 153, 204));
        btn_reg11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pannel_acc_typeLayout = new javax.swing.GroupLayout(pannel_acc_type);
        pannel_acc_type.setLayout(pannel_acc_typeLayout);
        pannel_acc_typeLayout.setHorizontalGroup(
            pannel_acc_typeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannel_acc_typeLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(pannel_acc_typeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pannel_acc_typeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_reg11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_reg9, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pannel_acc_typeLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannel_acc_typeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_reg10, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addGap(88, 88, 88))
        );
        pannel_acc_typeLayout.setVerticalGroup(
            pannel_acc_typeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannel_acc_typeLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel11)
                .addGap(29, 29, 29)
                .addComponent(btn_reg9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btn_reg11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btn_reg10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        tabs.addTab("tab5", pannel_acc_type);

        jPanel3.add(tabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, -40, 500, 650));
        tabs.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1014, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    private void btn_reg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg2ActionPerformed
        tabs.setSelectedIndex(4);
    }//GEN-LAST:event_btn_reg2ActionPerformed

    private void btn_reg3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg3ActionPerformed
        tabs.setSelectedIndex(2);
    }//GEN-LAST:event_btn_reg3ActionPerformed

    private void btn_reg_cusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg_cusActionPerformed
           
          Con = ob1.getConnection();
            
            
        
            String name = txt_name.getText();
            String psw = txt_pw.getText();
            String pw = txt_pw_con.getText();//confirmation
            
            //checking all fields are filled
             if (txt_name.getText().isEmpty() || txt_pw.getText().isEmpty()||txt_pw_con.getText().isEmpty()) {
                
                 JOptionPane.showMessageDialog(null, "Fill all the Fields!", "Info", JOptionPane.INFORMATION_MESSAGE);
             
             }else{
             //check pw and pw confimations are equal 
             if (psw == null ? pw == null : psw.equals(pw))
            {
                System.out.println("passwords are equal");
            }else
            {
                JOptionPane.showMessageDialog(null, "Registed Unsuccess! Check password Confirm", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
            
            try{
                //customer table
                psmt = Con.prepareStatement("Insert into register(user_name,password)values(?,?)");
                psmt.setString(1, name);
                psmt.setString(2,pw);
                psmt.executeUpdate();
                
                
                
                
                psmt = Con.prepareStatement("Insert into personal(name,password)values(?,?)");
                psmt.setString(1, name);
                psmt.setString(2,pw);
                psmt.executeUpdate();
                System.out.println("done test 2");
                
                //tabedpane tab index                
                tabs.setSelectedIndex(3);
                
                
                JOptionPane.showMessageDialog(null, "Registed Success!", "Info", JOptionPane.INFORMATION_MESSAGE);
                tabs.setSelectedIndex(0);
               } catch (SQLException ex) {
                
                   JOptionPane.showMessageDialog(rootPane, ex);
                   System.out.println(ex);
             
             }
            
            
            
        }
            
    }//GEN-LAST:event_btn_reg_cusActionPerformed

    private void btn_reg5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg5ActionPerformed
        tabs.setSelectedIndex(4);
    }//GEN-LAST:event_btn_reg5ActionPerformed

    private void btn_reg_comActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg_comActionPerformed
       
        Con = ob1.getConnection();
        
        String com_name = txt_com_name.getText();
        String com_psw = txt_com_pw.getText();
        String com_pw =txt_com_pw_con.getText();
        
        if(txt_com_name.getText().isEmpty()||txt_com_pw.getText().isEmpty()||txt_com_pw_con.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "fields cannot be empty!");
        }else{
        
            if(com_psw.equals(com_pw)){
        try{
            //company reg
             psmt=Con.prepareStatement("Insert into register_com(com_name,pw)values(?,?)");
             psmt.setString(1,com_name);
             psmt.setString(2, com_pw);
             psmt.executeUpdate();
             
             psmt=Con.prepareStatement("CREATE table `"+com_name+"`(com_name varchar(20) PRIMARY KEY,service text,price double);");
             psmt.executeUpdate();
             
            JOptionPane.showMessageDialog(rootPane, "Registration succsess!");
            txt_com_name.setText(null);
            txt_com_pw.setText(null);
            txt_com_pw_con.setText(null);
            
        }catch(Exception e)
        {
           JOptionPane.showMessageDialog(rootPane, e);
            System.out.println(e);
        }
        }else{
                JOptionPane.showMessageDialog(rootPane, "passwods not match!");
            }
        
        }
        
    }//GEN-LAST:event_btn_reg_comActionPerformed

    private void btn_reg8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg8ActionPerformed
       tabs.setSelectedIndex(4);
    }//GEN-LAST:event_btn_reg8ActionPerformed

    private void btn_reg9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg9ActionPerformed
        tabs.setSelectedIndex(3);
    }//GEN-LAST:event_btn_reg9ActionPerformed

    private void btn_reg10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg10ActionPerformed
        tabs.setSelectedIndex(0);
    }//GEN-LAST:event_btn_reg10ActionPerformed

    private void btn_reg11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg11ActionPerformed
        tabs.setSelectedIndex(1);
    }//GEN-LAST:event_btn_reg11ActionPerformed

    private void btn_reg12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg12ActionPerformed
        Con = ob1.getConnection();
        
        String name = txt_user_name.getText();
        String pw = txt_pw_login.getText();
        
        
        
        if(name.isEmpty()||pw.isEmpty()){
            
            JOptionPane.showMessageDialog(rootPane, "Enter user name and password to login!");
            
        }else
        try
        {
            if(service_provider_tgl.isSelected()){
            //company login
             psmt =  Con.prepareStatement("Select * from register_com WHERE com_name = ? AND pw = ?");
             psmt.setString(1, name);
             psmt.setString(2,pw);
             
             ResultSet rs = psmt.executeQuery();
             
             if(rs.next()){
                 
                 service_provider s1 = new service_provider();
                 s1.setVisible(true);
                 this.dispose();
             
             }else
             {
               JOptionPane.showMessageDialog(rootPane, "Invalid username or password.");                 
             }
            
            }else{
                //customer login
           psmt = Con.prepareStatement("Select * from register WHERE user_name = ? AND password = ?");
           psmt.setString(1,name);
           psmt.setString(2, pw);
           psmt.executeQuery();
           
           
           ResultSet rs = psmt.executeQuery();
           
           if (rs.next()) {
                
                 Customer c1 = new Customer();
                 c1.setVisible(true);
                 this.dispose();
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "Invalid username or password.");
            }
            }
           
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_reg12ActionPerformed

    private void btn_reg13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg13ActionPerformed
        tabs.setSelectedIndex(0);
    }//GEN-LAST:event_btn_reg13ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
       this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btn_reg10;
    private com.k33ptoo.components.KButton btn_reg11;
    private com.k33ptoo.components.KButton btn_reg12;
    private com.k33ptoo.components.KButton btn_reg13;
    private com.k33ptoo.components.KButton btn_reg2;
    private com.k33ptoo.components.KButton btn_reg3;
    private com.k33ptoo.components.KButton btn_reg5;
    private com.k33ptoo.components.KButton btn_reg8;
    private com.k33ptoo.components.KButton btn_reg9;
    private com.k33ptoo.components.KButton btn_reg_com;
    private com.k33ptoo.components.KButton btn_reg_cus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel panel_login;
    private javax.swing.JPanel pannel_acc_type;
    private javax.swing.JPanel pnl_register;
    private javax.swing.JPanel pnl_start;
    private toggle.ToggleButton service_provider_tgl;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTextField txt_com_name;
    private javax.swing.JTextField txt_com_pw;
    private javax.swing.JPasswordField txt_com_pw_con;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_pw;
    private javax.swing.JPasswordField txt_pw_con;
    private javax.swing.JPasswordField txt_pw_login;
    private javax.swing.JTextField txt_user_name;
    // End of variables declaration//GEN-END:variables
}
